### ISSUE TITLE
Support detection of Spring MVC request parameters annotated with @RequestBody

### ISSUE THREAD

**Issue by maqsoodmushtaq** [secdec/astam-correlator#2]
I tried **attack-surface-detector-cli** to scan a Java Spring based microservice service. It is a great tool that discovered all endpoints and created the output in JSON file.

This information is great for pen testers. However it does not pick up the ```@RequestBody``` annotation. 
 
I am wondering if the tool can be enhanced for Spring MVC such that a user could specify a set of annotations to be scanned and included in the output (console, JSON file etc)?

e.g.
```
> java -jar attack-surface-detector-cli.jar C:\...\SourceCode -additional_annotations=[list-of-annotations] -json -output-file=C:\...\endpoints.json
```

Idea is to collect as much information as possible about a given microservice APIs so that pen testers need minimal information from developers.

**Comment by tylercamp** [comment]
Hey @maqsoodmushtaq - since the module works on many different frameworks (not just Spring MVC), we'd like to avoid framework-specific parameters. Instead, I'll look into adding that annotation for the Spring MVC parser. Are there any sample open-source projects using the `@RequestBody` annotation we could use for testing?

**Comment by maqsoodmushtaq** [comment]
Hi @tylercamp, thanks for getting back to me. Even addition of @RequestBody will be great enhancement! I found some examples in [springfox project (petstore/controller)](https://github.com/springfox/springfox/tree/35e14270ca628fa5f40beac962035a3589074c4e/springfox-petstore/src/main/java/springfox/petstore/controller)

**Comment by tylercamp** [comment]
Thanks for the sample project, I'll take a look and let you know when I have any updates.

What issues are you seeing at the moment with `@RequestBody`? Is it preventing endpoints or parameters from being detected, or both? Do you think `@ResponseBody` something that should also be addressed here?

**Comment by maqsoodmushtaq** [comment]
Tool is successfully discovering all endpoints with path variables (@PathVariable) and request parameters (@RequestParam) where they are present.

However if @RequestBody annotation is also present it is not picked by the scan. @RequestBody annotation maps the HttpRequest body to a data transfer object (DTO). If CLI can read it and provide info in the JSON, it will help any caller of api to specify the DTO in the request body.

For example CLI detects the userId and sessionId path variables from snippet below but does not pickup finishPurchaseRequest object.

```
    @RequestMapping(value = "store/{storeId}/user_sessions/{sessionId}/finish", method = RequestMethod.POST)
    public Receipt finishPurchase(@PathVariable UUID userId,
                                @PathVariable UUID sessionId,
                                @RequestBody FinishPurchaseRequest finishPurchaseRequest) {
              // process request
    }
```

@ResponseBody does not need to be addressed. @ResponseBody tells a controller that the object returned is automatically serialized into JSON and passed back into the HttpResponse object. However that is also the default behaviour whether @ResponseBody is present or not.

A really useful one to add will be authorization annotations i.e any annotation starting with @Authorization e.g @AuthorizationScope or @Authorize e.g @AuthorizeWhen.
These annotation when specified on an endpoint provide information (a) this endpoint need authorization (b) what is required for authorization.

**Comment by tylercamp** [comment]
Thanks again, this info is very helpful. We have some authorization detection stuff already but it's legacy and I don't remember how it's being used off the top of my head.

I've raised the issue with a coordinator and will let you know when we've got an estimate for completion.

If you'd like to take a stab at the issue yourself and submit a pull request, the relevant file is here: https://github.com/secdec/astam-correlator/blob/master/threadfix-ham/src/main/java/com/denimgroup/threadfix/framework/impl/spring/SpringControllerEndpointParser.java#L186

**Comment by maqsoodmushtaq** [comment]
Thanks @tylercamp will try the pr if I have capacity.

**Comment by tylercamp** [comment]
@maqsoodmushtaq I expect to be starting on this some time on Friday. We may want to split this out into two issues - one for the `@RequestBody` and one for the authorization annotations, depending on how big the latter ends up being.

**Comment by maqsoodmushtaq** [comment]
@tylercamp sounds good! I can help validate the change on my side.

**Comment by tylercamp** [comment]
@maqsoodmushtaq I added support for the `@RequestBody` annotation and fixed a couple of other things - these changes are available on the [1.3.6-SNAPSHOT](https://github.com/secdec/astam-correlator/tree/1.3.6-SNAPSHOT) branch. It handles the cases I could find in that sample project, let me know if it works for your case too. You can build it with `mvn clean install` and get the relevant JARs from `threadfix-ham/target/...` and `threadfix-entities/target/...`

I've been looking around for examples on the use of `AuthorizationScope` and `AuthorizeWhen` but haven't been able to find any solid references, could you point me in the right direction on those?

**Comment by maqsoodmushtaq** [comment]
Hi Tyler,

Great!, I will give it a go. 

Regarding Authorization, I took the example of ```@AuthorizationScope``` from springfox project. Looks like the name could vary based on implementation.

Note that springfox is also an api documentation projects that aims to create docs in json format and render them using swagger - [example](https://dzone.com/articles/spring-boot-restful-api-documentation-with-swagger). 

Perhaps wildcard scan of ```@Authoriz``` annotation discover most info?

**Comment by tylercamp** [comment]
We'd prefer to have exact matching for specific annotation names and their associated packages, since different annotations could have different parameter types/names/ordering. There is some precedence for this in the Struts parsing, where we have plugin detection that supports a few of the most common Struts plugins and their annotations/types.

Optimally this would be in a different issue, with the framework name(s), attribute names, a description of how those APIs are used by a spring dev, and a (reasonably exact) example of what sort of information we would like to get out of it.

**Comment by tylercamp** [comment]
Hey @maqsoodmushtaq - just realized I may have forgotten to push that branch, `1.3.6-SNAPSHOT` is now (definitely) available on github here

**Comment by tylercamp** [comment]
@maqsoodmushtaq Just happened to take another look at this issue, since there are no more reported problems I'll plan to close this by EOD Friday (unless something else comes up)

**Comment by tylercamp** [comment]
Version 1.3.6 has been released with the mentioned update.
